name: Post JSON File to Two URLs

on:
  push:
    branches:
      - main  # Runs only when pushing to the main branch
  workflow_dispatch:  # Allows manual trigger

jobs:
  post_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Send JSON Data to First URL
        run: |
          curl -X POST "https://:MYC2tK88QwaD8pAnnbL6Lg@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:oNPvBhtcTZ2tM0vccV81aA/streams/AQAAAIiRD9CFrEobh2DK1_cGSyIAAAAA" \
          -H "Content-Type: application/json" \
          -d @stream.json

      - name: Send JSON Data to Second URL
        run: |
          curl -X POST "https://:5IE2NehZRbm4SyTQePayhw@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:oNPvBhtcTZ2tM0vccV81aA/streams/AQAAAKwROwDKz0UClOwjKg8ovoAAAAAA" \
          -H "Content-Type: application/json" \
          -d @stream.json
